package me.dyaika.marketplace.requests;

import lombok.Data;

import java.util.List;

@Data
public class CreateItemRequest {

    private String itemName;
    private String itemDescription;
    private Integer categoryId;
    private List<ItemParameterRequest> parameters;

    // Constructors, getters, and setters (generated by Lombok)
}