package me.dyaika.marketplace.requests;

import lombok.Data;

@Data
public class ItemParameterRequest {

    private String parameterName;
    private String parameterValue;

    // Constructors, getters, and setters (generated by Lombok)
}
