package me.dyaika.marketplace.dto.requests;

import lombok.Data;
import me.dyaika.marketplace.dto.ItemParameter;

import java.util.List;

@Data
public class CreateItemRequest {

    private String itemName;
    private String itemDescription;
    private Integer categoryId;
    private List<ItemParameter> parameters;

    // Constructors, getters, and setters (generated by Lombok)
}