package me.dyaika.marketplace.dto;

import lombok.Data;

@Data
public class ItemParameter {

    private String parameterName;
    private String parameterValue;

    // Constructors, getters, and setters (generated by Lombok)
}
