version: '3.0'

services:  
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: marketplaceDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
      
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./marketplace
      dockerfile: Dockerfile
    ports:
      - "80:8000"